<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE moversreport [
<!ELEMENT moversreport (types,datethreshold,enddatethreshold,daterun,up?,down?)>
<!ELEMENT types (#PCDATA)>
<!ELEMENT datethreshold (#PCDATA)>
<!ELEMENT enddatethreshold (#PCDATA)>
<!ELEMENT daterun (#PCDATA)>
<!ELEMENT up (file+)>
<!ELEMENT down (file+)>
<!ELEMENT file (diff+)>
<!ATTLIST file name CDATA #REQUIRED>
<!ATTLIST file path CDATA #REQUIRED>
<!ELEMENT diff EMPTY>
<!ATTLIST diff previousrun CDATA #REQUIRED>
<!ATTLIST diff currentrun CDATA #REQUIRED>
<!ATTLIST diff type CDATA #REQUIRED>
<!ATTLIST diff previouserrors CDATA #REQUIRED>
<!ATTLIST diff currenterrors CDATA #REQUIRED>
<!ATTLIST diff diff CDATA #REQUIRED>
]>
<moversreport>
 <types>checkstyle,pmd,findbugs,cobertura-line,cobertura-branch</types>
 <datethreshold>2020-01-20 07:10:12</datethreshold>
 <enddatethreshold>2020-01-22 13:10:12</enddatethreshold>
 <daterun>2020-01-22 13:10:12</daterun>
 <up>
 </up>
 <down>
 </down>
</moversreport>